# Generated by Django 5.1.2 on 2025-03-16 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchango', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionpage',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at', 'status')},
        ),
        migrations.AlterModelOptions(
            name='pledge',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': 'created_at', 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='pledge',
            unique_together={('user', 'page')},
        ),
        migrations.AlterField(
            model_name='contributionpage',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='to_pay_by',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Contribution', 'Contribution'), ('Pledge', 'Pledge'), ('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], default='Contribution', max_length=50),
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='status',
        ),
    ]
