# Generated by Django 5.1.2 on 2025-03-17 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mchango', '0002_alter_contributionpage_options_alter_pledge_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaB2C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result_parameters', models.JSONField(blank=True, null=True)),
                ('result_type', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.CharField(blank=True, max_length=50, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('registered_customer', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_party_public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('b2c_charges_paid_account_available_funds', models.CharField(blank=True, max_length=100, null=True)),
                ('b2c_utility_account_available_funds', models.CharField(blank=True, max_length=100, null=True)),
                ('b2c_working_account_available_funds', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_b2cs', to='mchango.contributionpage')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_b2cs', to='mchango.status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_b2cs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaC2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_date', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('business_shortcode', models.CharField(blank=True, max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('org_acc_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('thirdparty_trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_c2bs', to='mchango.contributionpage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_c2bs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaSTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('result_code', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_date', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stkss', to='mchango.contributionpage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
